#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 12 23:09:49 2022

@author: drogotti
"""

# Import packages 

from sqlalchemy import create_engine
import sqlalchemy
import pandas as pd 

#Connect to SQL instance 

MYSQL_HOSTNAME = '52.186.152.100' 
MYSQL_USER = 'Pedro'
MYSQL_PASSWORD = '93553436nbA!'
MYSQL_DATABASE = 'E2E'

connection_string = f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOSTNAME}/{MYSQL_DATABASE}'
engine = create_engine(connection_string)

#Load CSV File 

csvfile = pd.read_csv('/Users/drogotti/Downloads/COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_Facility.csv')
csvfile.to_sql('COVID-19', con=engine, if_exists ='append') 


# Create Trigger 

SELECT * FROM COVID LIMIT 20;
DELIMITER $$
CREATE TRIGGER COVID_concern_trigger BEFORE INSERT ON Covid19
FOR EACH ROW 
BEGIN IF NEW.alert >=5 THEN
SIGNAL SQLSTATE '50000'
SET MESSAGE_TEXT = 'Covid patient impact should be between 0 and 5. Please try again.'
;END IF;
END; $$